# Generated by Django 3.2 on 2021-05-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='user name')),
                ('taku', models.CharField(max_length=10, verbose_name='taku')),
                ('mdate', models.DateTimeField(verbose_name='match date')),
                ('rank', models.IntegerField(verbose_name='match rank')),
                ('jikaze', models.CharField(max_length=3, verbose_name='jikaze')),
                ('result_point', models.IntegerField(verbose_name='result point')),
                ('rank_point', models.IntegerField(verbose_name='rank point')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='user name')),
                ('total_point', models.IntegerField(verbose_name='total point')),
                ('taku', models.CharField(max_length=10, verbose_name='taku')),
            ],
        ),
    ]
