# Generated by Django 3.2 on 2021-05-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jantama_app', '0002_remove_user_taku'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='total_point',
            field=models.IntegerField(default=2, verbose_name='total point'),
            preserve_default=False,
        ),
    ]
