# Generated by Django 3.2 on 2021-05-08 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jantama_app', '0003_match_total_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='jikaze',
        ),
    ]
