# Generated by Django 3.2 on 2021-05-10 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jantama_app', '0004_remove_match_jikaze'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='half',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='match',
            name='rank',
            field=models.CharField(max_length=10, verbose_name='match rank'),
        ),
    ]
