# Generated by Django 3.2 on 2021-05-10 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jantama_app', '0005_auto_20210510_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='mdate',
            field=models.DateField(verbose_name='match date'),
        ),
    ]
