# Generated by Django 3.2 on 2021-05-10 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jantama_app', '0008_auto_20210510_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='total_point',
            new_name='now_rank_point',
        ),
        migrations.AddField(
            model_name='user',
            name='now_dan',
            field=models.CharField(default='shi1', max_length=10, verbose_name='user name'),
        ),
        migrations.AlterField(
            model_name='match',
            name='dan',
            field=models.CharField(default='shi1', max_length=10, verbose_name='now danni'),
        ),
        migrations.AlterField(
            model_name='match',
            name='taku',
            field=models.CharField(default='bronze', max_length=10, verbose_name='taku'),
        ),
    ]
