# Generated by Django 3.2 on 2021-05-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jantama_app', '0009_auto_20210510_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='now_totap_point',
            field=models.IntegerField(default=525, verbose_name='now Total point'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='imput name', max_length=10, verbose_name='user name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='now_dan',
            field=models.CharField(default='shi1', max_length=10, verbose_name='now dan-i'),
        ),
        migrations.AlterField(
            model_name='user',
            name='now_rank_point',
            field=models.IntegerField(verbose_name='now dan-i point'),
        ),
    ]
