# Generated by Django 3.2 on 2021-05-10 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jantama_app', '0010_auto_20210510_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='now_totap_point',
            new_name='now_total_point',
        ),
    ]
