# Generated by Django 3.2 on 2021-05-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jantama_app', '0011_rename_now_totap_point_user_now_total_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='now_total_point_without_shoki',
            field=models.IntegerField(default=10000, verbose_name='初期ポイントを除いた累計ポイント'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match',
            name='name',
            field=models.CharField(default='sample', max_length=10, verbose_name='user name'),
        ),
        migrations.AlterField(
            model_name='match',
            name='taku',
            field=models.CharField(default='silver', max_length=10, verbose_name='taku'),
        ),
        migrations.AlterField(
            model_name='user',
            name='now_total_point',
            field=models.IntegerField(verbose_name='初期ポイントを含む累計ポイント'),
        ),
    ]
