# Generated by Django 3.2 on 2021-05-10 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jantama_app', '0012_auto_20210510_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='now_total_point_without_shoki',
        ),
    ]
